//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApptest1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int id_Comment { get; set; }
        public int id_Game { get; set; }
        public int id_User { get; set; }
        public System.DateTime Date_comment { get; set; }
        public string Comment_text { get; set; }
        public int Rating_id { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Users Users { get; set; }
        public virtual Games Games1 { get; set; }
        public virtual Rating_Values Rating_Values { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
