//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApptest1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.Comments = new HashSet<Comments>();
            this.Comments1 = new HashSet<Comments>();
        }
    
        public int id_Game { get; set; }
        public string Name { get; set; }
        public System.DateTime Publication_date { get; set; }
        public int id_Platform { get; set; }
        public int id_Genre { get; set; }
        public int id_Developer { get; set; }
        public int id_Image_preview { get; set; }
        public Nullable<int> Rating_average { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments1 { get; set; }
        public virtual Developer_id Developer_id { get; set; }
        public virtual Genres_id Genres_id { get; set; }
        public virtual id_sourse_image_preview id_sourse_image_preview { get; set; }
        public virtual Platform_id Platform_id { get; set; }
    }
}
