//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApptest1.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class asd1234Entities : DbContext
    {
        private static asd1234Entities _context;


        public static asd1234Entities GetContex()
        {
            if (_context == null)
                _context = new asd1234Entities();
            return _context;
        }
        public asd1234Entities()
            : base("name=asd1234Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Developer_id> Developer_id { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<Genres_id> Genres_id { get; set; }
        public virtual DbSet<id_sourse_image_preview> id_sourse_image_preview { get; set; }
        public virtual DbSet<Platform_id> Platform_id { get; set; }
        public virtual DbSet<Rating_Values> Rating_Values { get; set; }
        public virtual DbSet<Role_id> Role_id { get; set; }
        public virtual DbSet<Sex_id> Sex_id { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
